[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.ci]
fuzz.runs = 1000
verbosity = 4

[profile.lite]
optimizer = false
via_ir = false

[profile.test]
via_ir = false
src = "test"

[etherscan]
avalanche = { key = "${SNOWTRACE_API_KEY}" }
fuji = { key = "${SNOWTRACE_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
