[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.25"
evm_version = 'shanghai'
test = 'tests'
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200
via_ir = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = 'preserve'
multiline_func_header = 'params_first'
quote_style = 'double'
number_underscores = 'thousands'
override_spacing = true
wrap_comments = false

[profile.ci]
fuzz.runs = 1000
verbosity = 4

[profile.lite]
optimizer = false
via_ir = false

[profile.test]
via_ir = false
src = "test"

[etherscan]
avalanche = { key = "${SNOWTRACE_API_KEY}" }
fuji = { key = "${SNOWTRACE_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
